runtime: nodejs18
instance_class: F1

handlers:
- url: /api/.*
  script: auto
  secure: always

- url: /.*
  static_files: index.html
  upload: index.html
  secure: always

env_variables:
  NODE_ENV: production
